services:
  api:
    image: ${DOCKER_REGISTRY-}rabbitmq-course-api
    build:
      context: .
      dockerfile: RabbitMQ.Course.Api/Dockerfile
    networks:
      backend:
  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    ports:
      - 15672:15672
    networks:
      backend:

networks:
  backend:
