services:
  publisher:
    image: ${DOCKER_REGISTRY-}rabbitmq-course-publisher
    build:
      context: .
      dockerfile: RabbitMQ.Course.Publisher/Dockerfile
    environment:
      - RABBIT_MQ_HOST=${RABBIT_MQ_HOST}
      - RABBIT_MQ_USERNAME=${RABBIT_MQ_USERNAME}
      - RABBIT_MQ_PASSWORD=${RABBIT_MQ_PASSWORD}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      backend:
  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_MQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_PASSWORD}
    healthcheck:
      test: ["CMD", "rabbitmqctl", "ping"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    networks:
      backend:

networks:
  backend:
