services:
  publisher:
    image: ${DOCKER_REGISTRY-}rabbitmq-course-publisher
    build:
      context: .
      dockerfile: RabbitMQ.Course.Publisher/Dockerfile
    environment:
      - RABBIT_MQ_HOST=${RABBIT_MQ_HOST}
    networks:
      backend:
  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    ports:
      - 15672:15672
    networks:
      backend:

networks:
  backend:
